source 'http://api.berkshelf.com'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'chef-client'
cookbook 'dpkg_packages', git: 'https://github.com/brodock/chef-dpkg_packages.git'
cookbook 'locale', git: 'https://github.com/brodock/chef-locale.git'
cookbook 'git', git: 'https://github.com/brodock/git.git'
cookbook 'htop'
cookbook 'imagemagick'
cookbook 'mysql', '4.0.20'
cookbook 'mariadb', git: 'https://github.com/joerocklin/chef-mariadb.git'
cookbook 'mumble', git: 'https://github.com/brodock/chef-mumble.git'
cookbook 'nodejs'
cookbook 'omnibus_updater'
cookbook 'nginx'
cookbook 'passenger_nginx', git: 'http://github.com/brodock/chef-passenger_nginx.git'
cookbook 'php-fpm', git: 'https://github.com/brodock/chef-php-fpm.git'
cookbook 'ruby', git: 'https://github.com/brodock/chef-ruby.git'
cookbook 'ruby_install'
cookbook 'redis', git: 'https://github.com/brodock/chef-redis.git'
cookbook 'ubuntu', git: 'https://github.com/brodock/chef-ubuntu.git'
cookbook 'user', git: 'https://github.com/fnichol/chef-user.git'
cookbook 'vim'
