site :opscode

cookbook 'apt'
cookbook 'build-essential'
cookbook 'chef-client'
cookbook 'chruby', git: 'https://github.com/fnichol/chef-chruby.git'
cookbook 'dpkg_packages', git: 'https://github.com/brodock/chef-dpkg_packages.git'
cookbook 'locale', git: 'https://github.com/Agiley/chef-locale.git'
cookbook 'git', git: 'https://github.com/brodock/git.git'
cookbook 'htop'
cookbook 'imagemagick'
cookbook 'mysql'
cookbook 'nodejs'
cookbook 'omnibus_updater'
cookbook 'passenger_nginx', git: 'http://github.com/brodock/chef-passenger_nginx.git'
cookbook 'ruby', git: 'https://github.com/brodock/chef-ruby.git'
cookbook 'ruby_build', git: 'https://github.com/brodock/chef-ruby_build.git'
cookbook 'ubuntu', git: 'https://github.com/brodock/chef-ubuntu.git'
cookbook 'user', git: 'https://github.com/fnichol/chef-user.git'
cookbook 'vim'
